// AUTO-GENERATED by scripts/generate-tool-tests.ts — do not edit manually.
// Integration test for pdf-protect — verifies manifest wiring + stages.
import { describe, it, expect } from 'vitest';
import { manifest, inputSchema } from '@/tools/pdf/pdf-protect/manifest';
import { validationStage } from '@/tools/pdf/pdf-protect/stages/validation';
import { processingStage } from '@/tools/pdf/pdf-protect/stages/processing';
import { downloadStage } from '@/tools/pdf/pdf-protect/stages/download';

describe('pdf-protect — integration', () => {
  it('manifest is well-formed', () => {
    expect(manifest.manifestVersion).toBe('1.0.0');
    expect(manifest.slug).toBe('pdf-protect');
    expect(manifest.category).toBe('pdf');
    expect(manifest.title).toBeTruthy();
    expect(manifest.description).toBeTruthy();
    expect(manifest.seo).toBeDefined();
    expect(manifest.seo.canonicalUrl).toContain('pdf/pdf-protect');
    expect(manifest.seo.openGraph).toBeDefined();
    expect(manifest.seo.twitterCard).toBeDefined();
    expect(manifest.seo.structuredData).toBeDefined();
    expect(manifest.limits).toBeDefined();
    expect(manifest.limits.maxInputSize).toBeGreaterThan(0);
    expect(manifest.limits.maxProcessingTime).toBeGreaterThan(0);
  });

  it('stages are wired in manifest', () => {
    expect(manifest.stages).toBeDefined();
    const stages = manifest.stages as {
      input: unknown;
      validation: unknown;
      processing: unknown;
      preview: unknown;
      download: unknown;
    };
    expect(stages.input).toBeDefined();
    expect(stages.validation).toBeDefined();
    expect(stages.processing).toBeDefined();
    expect(stages.preview).toBeDefined();
    expect(stages.download).toBeDefined();
  });

  it('inputSchema is callable', () => {
    const result = inputSchema.safeParse({});
    // Some tools accept empty input (e.g., uuid-generator) — only assert it returns a result
    expect(result).toBeDefined();
    expect(typeof result.success).toBe('boolean');
  });

  it('validation stage returns structured result', async () => {
    const result = await validationStage({});
    expect(result).toBeDefined();
    expect(typeof result.success).toBe('boolean');
    if (!result.success) {
      expect(result.errors.length).toBeGreaterThan(0);
      for (const err of result.errors) {
        // ToolError shape: { kind, cause, userMessage, field? }
        expect(err).toHaveProperty('kind');
        expect(err).toHaveProperty('cause');
        expect(err).toHaveProperty('userMessage');
        expect(err.userMessage).toHaveProperty('what');
        expect(err.userMessage).toHaveProperty('howToFix');
      }
    } else {
      expect(result.data).toBeDefined();
    }
  });

  it('processing stage is async', () => {
    // processingStage is async — verify it returns a Promise
    const ctx = {
      input: {} as never,
      signal: new AbortController().signal,
      onProgress: () => {},
      emit: () => {},
    };
    const result = processingStage(ctx);
    expect(result).toBeInstanceOf(Promise);
    // Catch to avoid unhandled rejection
    result.catch(() => {});
  });

  it('download stage is callable', () => {
    expect(typeof downloadStage).toBe('function');
  });

  it('seo has required fields', () => {
    expect(manifest.seo.title).toBeTruthy();
    expect(manifest.seo.description).toBeTruthy();
    expect(manifest.seo.keywords).toBeInstanceOf(Array);
    expect(manifest.seo.canonicalUrl).toMatch(/^https?:\/\//);
  });

  it('structured data is SoftwareApplication', () => {
    expect(manifest.seo.structuredData['@type']).toBe('SoftwareApplication');
    expect(manifest.seo.structuredData.name).toBeTruthy();
    expect(manifest.seo.structuredData.offers).toBeDefined();
    expect(manifest.seo.structuredData.offers['@type']).toBe('Offer');
    expect(manifest.seo.structuredData.offers.price).toBe('0');
  });

  it('related tools is array', () => {
    expect(Array.isArray(manifest.relatedTools)).toBe(true);
  });

  it('analytics has funnel steps', () => {
    expect(manifest.analytics.funnelSteps).toBeInstanceOf(Array);
    expect(manifest.analytics.funnelSteps.length).toBeGreaterThan(0);
  });

  it('does not require auth (LOCK-07: guest-first)', () => {
    expect(manifest.limits.requiresAuth).toBe(false);
    expect(manifest.limits.premiumOnly).toBe(false);
  });
});
