// AUTO-GENERATED by scripts/generate-tool-tests.ts — do not edit manually.
// Unit test for uuid-generator processing stage.
import { describe, it, expect } from 'vitest';
import { processingStage } from '@/tools/developer/uuid-generator/stages/processing';
import { validationStage } from '@/tools/developer/uuid-generator/stages/validation';
import { inputSchema, type ToolInput } from '@/tools/developer/uuid-generator/manifest';

describe('uuid-generator — unit', () => {
  it('has a processing stage that is a function', () => {
    expect(typeof processingStage).toBe('function');
  });

  it('has a validation stage that accepts input', async () => {
    const result = await validationStage({} as unknown);
    expect(result).toBeDefined();
    // Some tools (e.g., uuid-generator) have all-optional input and will succeed on empty input.
    // The contract here is just that validation returns a result object with a success field.
    expect(typeof result.success).toBe('boolean');
  });

  it('inputSchema is a Zod schema', () => {
    expect(inputSchema).toBeDefined();
    expect(typeof inputSchema.safeParse).toBe('function');
  });

  it('validation returns structured errors when input is insufficient', async () => {
    const result = await validationStage({} as unknown);
    if (!result.success) {
      expect(result.errors).toBeInstanceOf(Array);
      expect(result.errors.length).toBeGreaterThan(0);
      for (const err of result.errors) {
        // ToolError shape: { kind, cause, userMessage, field? }
        expect(err).toHaveProperty('kind');
        expect(err).toHaveProperty('cause');
        expect(err).toHaveProperty('userMessage');
        expect(err.userMessage).toHaveProperty('what');
        expect(err.userMessage).toHaveProperty('howToFix');
      }
    } else {
      // Tool accepts empty input (e.g., uuid-generator) — verify it returns data
      expect(result.data).toBeDefined();
    }
  });

  it('processing stage is async and returns a value or throws', async () => {
    // Validate a minimal input through the schema first
    // Note: each tool has its own input shape; we test the contract here.
    expect(processingStage).toBeDefined();
    // The processing stage should be callable with a context-like object
    // (it will likely throw on invalid input, which is acceptable for the contract test)
    try {
      const ctx = {
        input: {} as ToolInput,
        signal: new AbortController().signal,
        onProgress: () => {},
        emit: () => {},
      };
      await processingStage(ctx);
    } catch (err) {
      // Expected — invalid input
      expect(err).toBeDefined();
    }
  });

  it('uuid-generator — has valid slug/category/lifecycle', async () => {
    const mod = await import('@/tools/developer/uuid-generator/manifest');
    expect(mod.manifest.slug).toBe('uuid-generator');
    expect(mod.manifest.category).toBe('developer');
    // Lifecycle can be 'stable', 'beta', or 'development' — all are valid
    expect(['stable', 'beta', 'development']).toContain(mod.manifest.lifecycle);
    expect(mod.manifest.execution).toMatch(/^(browser|server)$/);
  });
});
