// db/seed.ts — Seed script for Supabase Production (Phase 2 Sprint 6).
// Seeds feature flags and tool metadata for the 23 production tools.
// Run via: bun run db/seed.ts (requires DATABASE_URL env var).

import { allManifests } from '../src/generated/registry';

const FEATURE_FLAGS_SEED = [
  { key: 'admin-console', description: 'Admin console visibility', enabled: true, rollout_percentage: 100 },
  { key: 'history-persistence', description: 'Persist tool history locally', enabled: true, rollout_percentage: 100 },
  { key: 'share-links', description: 'Generate shareable links for tools', enabled: true, rollout_percentage: 100 },
  { key: 'analytics-consent-banner', description: 'Show analytics consent banner', enabled: true, rollout_percentage: 100 },
  { key: 'command-palette', description: 'Enable command palette (Cmd+K)', enabled: true, rollout_percentage: 100 },
  { key: 'recently-viewed', description: 'Track recently viewed tools', enabled: true, rollout_percentage: 100 },
  { key: 'undo-actions', description: 'Enable undo for destructive actions', enabled: true, rollout_percentage: 100 },
  { key: 'autosave-preferences', description: 'Autosave user preferences', enabled: true, rollout_percentage: 100 },
];

const TOOL_METADATA_SEED = allManifests.map((m) => ({
  slug: m.slug,
  category: m.category,
  display_name: m.title,
  description: m.description,
  lifecycle: m.lifecycle,
  is_premium: m.limits.premiumOnly,
  requires_auth: m.limits.requiresAuth,
  config: {},
}));

// This script outputs seed SQL when run without a database connection.
// To run against a real database, set DATABASE_URL and use `psql` or Drizzle's push.
function main(): void {
  console.log('-- Seed data generated by db/seed.ts');
  console.log(`-- ${FEATURE_FLAGS_SEED.length} feature flags`);
  console.log(`-- ${TOOL_METADATA_SEED.length} tool metadata rows`);
  console.log('');

  console.log('-- Feature Flags');
  for (const flag of FEATURE_FLAGS_SEED) {
    const desc = flag.description.replace(/'/g, "''");
    console.log(
      `insert into public.feature_flags (key, description, enabled, rollout_percentage) values ('${flag.key}', '${desc}', ${flag.enabled}, ${flag.rollout_percentage}) on conflict (key) do update set description = excluded.description, enabled = excluded.enabled, rollout_percentage = excluded.rollout_percentage;`,
    );
  }
  console.log('');

  console.log('-- Tool Metadata');
  for (const tool of TOOL_METADATA_SEED) {
    const desc = (tool.description ?? '').replace(/'/g, "''");
    const name = tool.display_name.replace(/'/g, "''");
    console.log(
      `insert into public.tool_metadata (slug, category, display_name, description, lifecycle, is_premium, requires_auth, config) values ('${tool.slug}', '${tool.category}', '${name}', '${desc}', '${tool.lifecycle}', ${tool.is_premium}, ${tool.requires_auth}, '{}'::jsonb) on conflict (slug) do update set display_name = excluded.display_name, description = excluded.description, lifecycle = excluded.lifecycle;`,
    );
  }
}

main();
